baseURL = "http://example.org/"
languageCode = "en-us"
title = "thapabishwa"
avatar = "https://github.com/thapabishwa.png"
pygmentsCodeFences = true
pygmentsUseClasses = true
Paginate = 20

[taxonomies]
tag = "tags"

[params]
author = "Bishwa Thapa"
description = "In solitude, where we are least alone."
github = "thapabishwa"
linkedin = "thapabishwa"
email = "thapabishwak@gmail.com"
url = "https://thapabishwa.github.io"
keywords = "blog, google analytics"
rss = false
lastmod = false
userStatusEmoji = "😀"
avatar = "https://github.com/thapabishwa.png"
# favicon = "/images/github.png"
favicon = "/fav.png"
useBootstrapCDN = true
location = "🇪🇸/🇳🇵"
enableGitalk = false
math = true

  [[params.links]]
  title = "Resume"
  href = "https://thapabishwa.github.io/cv"
  icon = "https://icons.getbootstrap.com/assets/icons/file-earmark-person.svg"

[frontmatter]
lastmod = [ "lastmod", ":fileModTime", ":default" ]

# [[module.imports]]
# path = "github.com/MeiK2333/github-style"

[[module.imports]]
path = "github.com/thapabishwa/hugo-profile"

[[module.imports]]
path = "github.com/netspective-studios/hugo-shortcode-diagram"

  [[module.imports.mounts]]
  source = "shortcodes"
  target = "layouts/shortcodes"

[markup.tableOfContents]
startLevel = 1
endLevel = 5
ordered = false

[markup.goldmark.renderer]
hardWraps = true

[[Menus.main]]
identifier = "blog"
name = "Blogs"
title = "Blog posts"
url = "/blogs"
weight = 2

[[Menus.main]]
identifier = "tags"
name = "Tags"
url = "/tags"
weight = 1

  [params.hero]
  enable = true
  intro = "Hi, my name is"
  title = "Bishwa Thapa"
  #subtitle = "I build things for the web"
  content = """
![Amazon AWS](https://img.shields.io/static/v1?style=for-the-badge&message=AWS&color=232F3E&logo=Amazon+AWS&logoColor=FFFFFF&label=)![Google Cloud](https://img.shields.io/static/v1?style=for-the-badge&message=GCP&color=4285F4&logo=Google+Cloud&logoColor=FFFFFF&label=)![Ubuntu](https://img.shields.io/static/v1?style=for-the-badge&message=Ubuntu/Debian&color=E95420&logo=Ubuntu&logoColor=FFFFFF&label=)![Arch Linux](https://img.shields.io/static/v1?style=for-the-badge&message=Arch&color=1793D1&logo=Arch+Linux&logoColor=FFFFFF&label=)![Cent OS](https://img.shields.io/badge/cent%20os-002260?style=for-the-badge&logo=centos&logoColor=F0F0F0)![Nginx](https://img.shields.io/badge/nginx-%23009639.svg?style=for-the-badge&logo=nginx&logoColor=white)
![Go](https://img.shields.io/static/v1?style=for-the-badge&message=Golang&color=00ADD8&logo=Go&logoColor=FFFFFF&label=)![Python](https://img.shields.io/badge/python-3670A0?style=for-the-badge&logo=python&logoColor=ffdd54)![Shell Script](https://img.shields.io/badge/shell_script-%23121011.svg?style=for-the-badge&logo=gnu-bash&logoColor=white)![Lua](https://img.shields.io/static/v1?style=for-the-badge&message=OpenResy+Lua&color=2C2D72&logo=Lua&logoColor=FFFFFF&label=)![Node.js](https://img.shields.io/static/v1?style=for-the-badge&message=Node&color=339933&logo=Node.js&logoColor=FFFFFF&label=)
![Postgres](https://img.shields.io/badge/postgres-%23316192.svg?style=for-the-badge&logo=postgresql&logoColor=white)![MySQL](https://img.shields.io/static/v1?style=for-the-badge&message=MySQL&color=4479A1&logo=MySQL&logoColor=FFFFFF&label=)![Redis](https://img.shields.io/badge/redis-%23DD0031.svg?style=for-the-badge&logo=redis&logoColor=white)![MongoDB](https://img.shields.io/badge/MongoDB-%234ea94b.svg?style=for-the-badge&logo=mongodb&logoColor=white)![Kafka](https://img.shields.io/static/v1?style=for-the-badge&message=Apache+Kafka&color=231F20&logo=Apache+Kafka&logoColor=FFFFFF&label=)
![Docker](https://img.shields.io/static/v1?style=for-the-badge&message=Docker&color=2496ED&logo=Docker&logoColor=FFFFFF&label=)![Kubernetes](https://img.shields.io/static/v1?style=for-the-badge&message=K8s&color=326CE5&logo=Kubernetes&logoColor=FFFFFF&label=)![Helm](https://img.shields.io/static/v1?style=for-the-badge&message=Helm&color=0F1689&logo=Helm&logoColor=FFFFFF&label=)![Prometheus](https://img.shields.io/static/v1?style=for-the-badge&message=Prometheus&color=E6522C&logo=Prometheus&logoColor=FFFFFF&label=)![Grafana](https://img.shields.io/static/v1?style=for-the-badge&message=Grafana&color=F46800&logo=Grafana&logoColor=FFFFFF&label=)![Elastic Stack](https://img.shields.io/static/v1?style=for-the-badge&message=ELK&color=005571&logo=Elastic+Stack&logoColor=FFFFFF&label=)
![Terraform](https://img.shields.io/badge/terraform-%235835CC.svg?style=for-the-badge&logo=terraform&logoColor=white)![Ansible](https://img.shields.io/badge/ansible-%231A1918.svg?style=for-the-badge&logo=ansible&logoColor=white)![Packer](https://img.shields.io/static/v1?style=for-the-badge&message=Packer&color=02A8EF&logo=Packer&logoColor=FFFFFF&label=)![Bugsnag](https://img.shields.io/static/v1?style=for-the-badge&message=Bugsnag&color=4949E4&logo=Bugsnag&logoColor=FFFFFF&label=)![PagerDuty](https://img.shields.io/static/v1?style=for-the-badge&message=PagerDuty&color=06AC38&logo=PagerDuty&logoColor=FFFFFF&label=)
![Jenkins](https://img.shields.io/badge/jenkins-%232C5263.svg?style=for-the-badge&logo=jenkins&logoColor=white)![Travis CI](https://img.shields.io/static/v1?style=for-the-badge&message=Travis+CI&color=3EAAAF&logo=Travis+CI&logoColor=FFFFFF&label=)![Concourse](https://img.shields.io/static/v1?style=for-the-badge&message=Concourse&color=3398DC&logo=Concourse&logoColor=FFFFFF&label=)![Argo](https://img.shields.io/static/v1?style=for-the-badge&message=Argo+CD&color=EF7B4D&logo=Argo&logoColor=FFFFFF&label=)![TeamCity](https://img.shields.io/badge/teamcity-000000.svg?style=for-the-badge&logo=teamcity&logoColor=white)
![Gitk](https://img.shields.io/badge/GitKraken-179287?style=for-the-badge&logo=GitKraken&logoColor=white)![GitHub](https://img.shields.io/static/v1?style=for-the-badge&message=GitHub&color=181717&logo=GitHub&logoColor=FFFFFF&label=)![Bitbucket](https://img.shields.io/static/v1?style=for-the-badge&message=Bitbucket&color=0052CC&logo=Bitbucket&logoColor=FFFFFF&label=)![Jira](https://img.shields.io/static/v1?style=for-the-badge&message=Jira++&color=0052CC&logo=Jira&logoColor=FFFFFF&label=)![Confluence](https://img.shields.io/static/v1?style=for-the-badge&message=Confluence&color=172B4D&logo=Confluence&logoColor=FFFFFF&label=)
  """
  image = "https://github.com/thapabishwa.png"

    [params.hero.button]
    enable = false
    name = "Resume"
    url = "/cv"
    download = false

[[params.hero.socialLinks.fontAwesomeIcons]]
icon = "fa fa-file-pdf"
url = "/cv"

[[params.hero.socialLinks.fontAwesomeIcons]]
icon = "fab fa-github"
url = "https://github.com/thapabishwa"

[[params.hero.socialLinks.fontAwesomeIcons]]
icon = "fab fa-linkedin"
url = "https://linkedin.com/in/thapabishwa"


[[params.hero.socialLinks.fontAwesomeIcons]]
icon = "fa fa-envelope"
url = "mailto:thapabishwak+home@gmail.com"


  [params.about]
  enable = false
  title = "About Me"
  # image = "https://github.com/thapabishwa.png"
  content = """
I am a software developer with a passion for web development. I have a background in computer science and mathematics, and I have a strong interest in the intersection of technology and art. I am currently working as a software developer at [example org.](https://example.com) in San Francisco, CA. 

I am currently working on a project that will be used to help people find the best way to get around the city."""

    [params.about.skills]
    enable = false
    title = "Here are a few technologies I've been working with recently:"
    items = [ "HTML", "CSS", "JavaScript", "React", "Node", "Express" ]

  [params.contact]
  enable = false
  content = "My inbox is always open. Whether you have a question or just want to say hi, I’ll try my best to get back to you!"
  email = "thapabishwak@gmail.com"
  btnName = "Mail me"
